# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('calibre', models.CharField(blank=True, max_length=20, null=True)),
                ('marca', models.CharField(blank=True, max_length=45, null=True)),
                ('categoria', models.CharField(choices=[('Fg', 'Arma de Fuego'), ('Bn', 'Arma Blanca'), ('Ot', 'Otro')], default='Ot', max_length=2)),
                ('objeto', models.CharField(max_length=45)),
                ('serial', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
    ]
