# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 00:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('calibre', models.CharField(max_length=20)),
                ('no_casquillos', models.SmallIntegerField(blank=True, null=True)),
                ('marca', models.CharField(blank=True, max_length=45, null=True)),
                ('categoria', models.BooleanField(null=None)),
                ('serial', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Arma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('objeto', models.CharField(max_length=45)),
            ],
        ),
        migrations.AddField(
            model_name='arma',
            name='Tipo_Arma_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Armas.Tipo_Arma'),
        ),
    ]
