# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-19 23:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Armas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arma',
            name='Tipo_Arma_id',
        ),
        migrations.AddField(
            model_name='arma',
            name='objeto',
            field=models.CharField(default=datetime.datetime(2016, 4, 19, 23, 0, 41, 268717, tzinfo=utc), max_length=45),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Tipo_Arma',
        ),
    ]
