# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 20:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Armas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arma',
            name='serial',
        ),
    ]
