# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-19 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Armas', '0002_auto_20160419_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arma',
            name='categoria',
            field=models.CharField(blank=True, max_length=30, null=None),
        ),
    ]
