# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Armas', '0004_auto_20160420_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arma',
            name='calibre',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
