# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Armas', '0005_auto_20160420_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arma',
            name='objeto',
            field=models.CharField(help_text='Herramienta utilizada para cometer el delito', max_length=45),
        ),
    ]
