# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Armas', '0006_auto_20160423_0113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arma',
            name='no_casquillos',
        ),
        migrations.AlterField(
            model_name='arma',
            name='objeto',
            field=models.CharField(max_length=45),
        ),
    ]
