# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 10:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Armas', '0001_initial'),
        ('localizaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('actividad', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(default='xx', max_length=55)),
                ('apellidos', models.CharField(default='xx', max_length=55)),
                ('edad', models.SmallIntegerField(blank=True, null=True)),
                ('muerto', models.BooleanField(null=None)),
                ('profesion', models.CharField(blank=True, max_length=45, null=True)),
                ('cui', models.CharField(blank=True, max_length=13, null=True)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('D', 'Desconocido')], default='D', max_length=2)),
                ('ubicacion', models.TextField()),
                ('no_casquillos', models.SmallIntegerField(blank=True, null=True)),
                ('fiscal', models.CharField(blank=True, max_length=60, null=True)),
                ('fecha', models.DateTimeField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('movil', models.CharField(max_length=100)),
                ('no_expediente', models.CharField(max_length=40)),
                ('Arma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Armas.Arma')),
                ('Municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localizaciones.Municipio')),
            ],
        ),
        migrations.AddField(
            model_name='actividad',
            name='Registro_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registros.Registro'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='Usuario_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
