# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 07:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Armas', '0001_initial'),
        ('home', '0002_auto_20160325_0011'),
        ('localizaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('actividad', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fiscal', models.CharField(blank=True, max_length=60, null=True)),
                ('fecha', models.DateTimeField()),
                ('descripcion', models.TextField()),
                ('movil', models.CharField(max_length=100)),
                ('no_expediente', models.CharField(max_length=40)),
                ('Arma_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Armas.Arma')),
                ('Localizacion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localizaciones.Localizacion')),
            ],
        ),
        migrations.CreateModel(
            name='Victima',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=55)),
                ('apellidos', models.CharField(max_length=55)),
                ('edad', models.SmallIntegerField()),
                ('muerto_herido', models.BooleanField(null=None)),
                ('profesion', models.CharField(blank=True, max_length=45, null=True)),
                ('cui', models.CharField(blank=True, max_length=13, null=True)),
                ('sexo', models.BooleanField(null=None)),
            ],
        ),
        migrations.AddField(
            model_name='registro',
            name='Victima_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registros.Victima'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='Registro_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registros.Registro'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='Usuario_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Usuario'),
        ),
    ]
