# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 01:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Registros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='victima',
            old_name='muerto_herido',
            new_name='muerto',
        ),
        migrations.AddField(
            model_name='registro',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 21, 1, 49, 13, 348728, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='victima',
            name='apellidos',
            field=models.CharField(default='xx', max_length=55),
        ),
        migrations.AlterField(
            model_name='victima',
            name='edad',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='victima',
            name='nombres',
            field=models.CharField(default='xx', max_length=55),
        ),
        migrations.AlterField(
            model_name='victima',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('D', 'Desconocido')], default='D', max_length=2),
        ),
    ]
