# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='serial',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
