# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-24 22:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Registros', '0002_registro_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 4, 24, 22, 44, 13, 860281, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
