# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registros', '0003_auto_20160421_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
