# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-22 01:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Registros', '0004_auto_20160421_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='ubicacion',
            field=models.TextField(default=datetime.datetime(2016, 4, 22, 1, 9, 15, 758310, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registro',
            name='Localizacion_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localizaciones.Municipio'),
        ),
    ]
