# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-22 01:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registros', '0005_auto_20160422_0109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro',
            old_name='Arma_id',
            new_name='Arma',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='Localizacion_id',
            new_name='Municipio',
        ),
    ]
