# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registros', '0006_remove_registro_localizacion_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
