# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 09:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registros', '0005_registro_is_active'),
        ('Registros', '0006_auto_20160422_0122'),
    ]

    operations = [
    ]
