# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registros', '0007_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='no_casquillos',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
