# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 07:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Localizacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=100)),
                ('tipo', models.BooleanField(null=None)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('Departamento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localizaciones.Departamento')),
            ],
        ),
        migrations.AddField(
            model_name='localizacion',
            name='Municipio_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localizaciones.Municipio'),
        ),
    ]
