# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 23:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localizaciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departamento',
            old_name='nombre',
            new_name='departamento',
        ),
        migrations.RenameField(
            model_name='localizacion',
            old_name='tipo',
            new_name='especifico',
        ),
        migrations.RenameField(
            model_name='municipio',
            old_name='nombre',
            new_name='municipio',
        ),
    ]
