# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 09:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localizaciones', '0002_auto_20160326_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localizacion',
            name='Municipio_id',
        ),
        migrations.DeleteModel(
            name='Localizacion',
        ),
    ]
