# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-22 01:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registros', '0005_auto_20160422_0109'),
        ('localizaciones', '0002_auto_20160326_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localizacion',
            name='Municipio_id',
        ),
        migrations.DeleteModel(
            name='Localizacion',
        ),
    ]
