# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 23:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=55)),
                ('apellidos', models.CharField(max_length=55)),
                ('contrasena', models.CharField(max_length=32)),
                ('institucion', models.CharField(blank=True, max_length=30)),
                ('ultima_conexion', models.DateTimeField(auto_now=True)),
                ('nombre_usuario', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('Tipo_Usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Tipo_Usuario')),
            ],
        ),
    ]
