# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 00:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Tipo_Usuario_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Tipo_Usuario'),
        ),
    ]
