# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20160405_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(max_length=254, unique=False),
        ),
    ]
