# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 03:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20160422_0153'),
        ('home', '0018_auto_20160423_0214'),
    ]

    operations = [
    ]
