# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 08:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_merge'),
        ('home', '0017_auto_20160423_0106'),
        ('home', '0020_auto_20160423_0552'),
    ]

    operations = [
    ]
